config/routes.rb
RongyiTermCms::Application.routes.draw do

  resources :projects

  root 'home#index'

  devise_for :admins, path: 'auth'

  mount Ckeditor::Engine => '/ckeditor'

  resources :admins  do
    member do
      post :update
      post :lock
      post :unlock
    end
  end

  # See how all your routes lay out with "rake routes".

  # You can have the root of your site routed with "root"
  #   root 'welcome#index'

  # Example of regular route:
  #   get 'official_article/:id' => 'official_article#destroy'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/views/layouts/_footer_js.html.erb
<script>
    App.init();
</script>
<%= yield :footer_js %>

app/views/layouts/_nav.html.erb
<div id="nav">
    <dl>
        <dt>
        <%= link_to '后台首页', root_path %>
        </dt>
    </dl>
    <% if can? :admin ,nil  %>
        <dl>
            <dt>
            <%= link_to '管理员', admins_path %>
            </dt>
        </dl>
    <% end %>
</div>

<div class="v-gap"></div>
<div id="nav-path">
    <%= link_to '首页', root_path %>
    <span> &nbsp;</span>
    <%= yield :nav_path %>
</div>

app/views/layouts/_notice.html.erb
<div id="notice" class="<%= flash[:notice_class] %>" data-notice="<%= flash[:notice] %>" >
</div>

app/views/layouts/_tools_bar.html.erb
<div class="v-gap"></div>
<div id="tools-bar">
    <a href="javascript:window.history.back();" >后退</a>
    <a href="javascript:window.location.href=window.location.href;"> 刷新</a>
    <%= yield :tools_bar %>
    <div id="search-bar">
        <%= yield :search_bar %>
    </div>
    <span class="right">
        <%= yield :top_paginate %>
    </span>
</div>

app/views/layouts/_user_bar.html.erb
<div id="user-bar">
    <% if admin_signed_in? %>
        <b> <%= current_admin.email %> </b>
        <%= link_to '退出', destroy_admin_session_path, method: :delete %>
    <% else %>
        <%= link_to '请登录', new_admin_session_path %>
        <%= link_to '免费注册', new_admin_registration_path %>
    <% end %>
</div>

app/views/layouts/application.html.erb
<!Doctype html>
<html>
    <head>
        <title> CMS</title>
        <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
        <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
        <%= csrf_meta_tags %>
    </head>
    <body>
        <%= render 'layouts/notice' %>
        <div id="header">
            <div class="top-bar">
                <%= render 'layouts/user_bar' %>
                终端机 后台管理
            </div>
            <%= render 'layouts/nav' %>
            <%= render 'layouts/tools_bar' %>
        </div>
        <div id="nav-move-more" class=" js-mouseover">
            <span class="more">菜单</span>
            <div class="nav-list shadow js-nav-list">
                <%= link_to '后台首页', root_path %>
            </div>
        </div>
        <div id="main">
            <%= yield %>
        </div>
        <div id="dialog"></div>
    </body>
</html>

<%= render 'layouts/footer_js' %>

app/views/layouts/application_devise.html.erb
<!Doctype html>
<html>
    <head>
        <title> CMS </title>
        <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
        <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
        <%= csrf_meta_tags %>
    </head>
    <body class="<%= @page_is %>">
        <%= render 'layouts/notice' %>
        <%= yield %>
    </body>    
</html>
    <%= render 'layouts/footer_js' %>